// DO NOT EDIT THIS FILE.
package com.algo.crud.controller;

import java.util.List;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
public class UtilController {

  @Autowired
  private JdbcTemplate jdbcTemplate;

  @DeleteMapping("/reset")
  public boolean reset() {

    // Delete all existing tables.
    List<String> tables = jdbcTemplate.queryForList("SHOW TABLES", String.class);
    for (String table : tables) {
        jdbcTemplate.execute("DROP TABLE IF EXISTS " + table);
    }

    String createTableSQL = "CREATE TABLE user (" +
    "id INT PRIMARY KEY AUTO_INCREMENT, " +
    "name VARCHAR(100) NOT NULL, " +
    "email VARCHAR(100) UNIQUE NOT NULL " +
    ")";

    jdbcTemplate.execute(createTableSQL);
    return true;
  }
}
